GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGF6YXJkIiwiaWF0IjoxNTg0NTk3MDc3LCJleHAiOjE1ODQ1OTcxMjJ9.UmxgDoPseOzp6cZYfWTGDvJ06jAex4H24CBb_FDQvlE

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGF6YXJkIiwiaWF0IjoxNTg0NTk2OTYyfQ.f0MvY3wzbDtWnEYhFarDOethBXGzzWuKR__A7dwqNGQ"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGF6YXJkIiwiaWF0IjoxNTg0NTk2OTYyfQ.f0MvY3wzbDtWnEYhFarDOethBXGzzWuKR__A7dwqNGQ"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Eden"
}